// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAT11jN_okiYIv9h8KBX3tTeQ39M2zk0AI',
    appId: '1:543193511735:web:912ea36d5e9e2de80b0cb2',
    messagingSenderId: '543193511735',
    projectId: 'flower-app-f8282',
    authDomain: 'flower-app-f8282.firebaseapp.com',
    storageBucket: 'flower-app-f8282.appspot.com',
    measurementId: 'G-1FGPY0S3L2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF1c0RcDjq8WyF3heDY44QRdzav6eWEgE',
    appId: '1:543193511735:android:21450a6e37926fb00b0cb2',
    messagingSenderId: '543193511735',
    projectId: 'flower-app-f8282',
    storageBucket: 'flower-app-f8282.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSwIyMMf1YU7KqXCu8rzh1Txg3sfyS0xI',
    appId: '1:543193511735:ios:adc9986bdbb2d3b90b0cb2',
    messagingSenderId: '543193511735',
    projectId: 'flower-app-f8282',
    storageBucket: 'flower-app-f8282.appspot.com',
    iosBundleId: 'com.fazo.flowerApp',
  );
}
